### ISSUE TITLE
Add integration tests for credential variations

### ISSUE THREAD

**Issue by theganyo** [apigee/apigee-remote-service-envoy#116]
Need to test app credential variations in integration:
- invalid api key
- invalid token request (client_id, secret, scope)
- credential not approved
- credential expired
- credential without correct product
- credential product not approved
- app not approved

**Comment by theganyo** [comment]
It will be possible for a token to be issued to have no products. For example, if a client passes valid credentials for an approved app but that happens to be associated with a rejected product, a token will be issued without no products.

**Comment by rockspore** [comment]
> It will be possible for a token to be issued to have no products. For example, if a client passes valid credentials for an approved app but that happens to be associated with a rejected product, a token will be issued without no products.

I am not able to fetch a token with the credentials from an approved App with all products rejected. Are you saying such a token will be possible after the resolution of https://github.com/apigee/apigee-remote-service-cli/issues/120?

**Comment by theganyo** [comment]
No, never mind that. I'll make sure it will mirror existing functionality.
