### ISSUE TITLE
Update to Envoy V3 APIs

### ISSUE THREAD

**Issue by rockspore** [apigee/apigee-remote-service-envoy#127]
Use the v3 apis to implement `Check` and `StreamAccessLogs` services.

**Comment by theganyo** [comment]
If possible, it would be nice to support both v2 and v3 as a transition to avoid incompatibility issues with envoy configs.

**Comment by rockspore** [comment]
> If possible, it would be nice to support both v2 and v3 as a transition to avoid incompatibility issues with envoy configs.

One solution I can think of by far is to implement both services and register them in the server.

**Comment by rockspore** [comment]
To summarize a bit:

Envoy 1.17 (to-be-released) will drop support of V2 APIs, which are the versions used by the adapter to implement the services.

And there are primarily two options:

* A hard switch to V3. This would be a breaking change which drops support of Envoy 1.14 and Istio 1.6, which uses Envoy 1.14.
* Adding V3 services beside V2 ones. This would maintain backward compatibility but introduce a lot of duplicate code.

@theganyo @srinandan

**Comment by srinandan** [comment]
How about this Proposal?

Adapter 1.4.x is the last version which supports v2.
Adapter 1.5.x supports v3 only. Works for Istio/ASM 1.8 and above (even 1.7?).

**Comment by theganyo** [comment]
I'm good with the break. Istio 1.6 is [no longer supported](https://istio.io/latest/about/supported-releases/), so I see no reason to continue to support v2 in ongoing versions.

**Comment by srinandan** [comment]
But Anthos Service Mesh 1.6 is still [supported](https://cloud.google.com/service-mesh/docs/supported-features). It is supported till the end of March.

**Comment by rockspore** [comment]
V3 is supported by Istio 1.7: https://github.com/istio/istio/issues/19885
