### ISSUE TITLE
ASM Istio Sidecar injection labeling in Hybrid example document.

### ISSUE THREAD

**Issue by rockspore** [apigee/apigee-remote-service-envoy#135]
The labeling to automatically inject sidecars to a namespace has changed in later versions of ASM. See: https://cloud.google.com/service-mesh/docs/proxy-injection?hl=en

The above link is for ASM 1.8 but I can also confirm this on ASM 1.7.

It does not affect open-source Istio.

We need to point this out in our Hybrid example (https://cloud.google.com/apigee/docs/api-platform/envoy-adapter/v1.4.x/example-hybrid) in case users are in a ASM cluster.

**Comment by theganyo** [comment]
Quick reference for readers here. The Istio way:

    kubectl label namespace NAMESPACE istio-injection=enabled --overwrite

The ASM way:

    kubectl label namespace NAMESPACE istio-injection- istio.io/rev=REVISION --overwrite
