### ISSUE TITLE
Make rejecting unauthorized call the default option

### ISSUE THREAD

**Issue by rockspore** [apigee/apigee-remote-service-envoy#149]
This can be achieved by changing the field in the config options from `reject_unauthorized` to `allow_unauthorized`. And in the CLI we will remove/comment out the RBAC filter.

The benefit of doing so is it allows users to receive more appropriate response status directly from the ext_authz service (the adapter) instead of the RBAC filter, which can only send 403 on access denial.

The reason this was not the default option before is that the access log service needs those headers added to the request by ext_authz filter, and those headers cannot be added to the request if it gets rejected directly by the adapter. However, with the ongoing effort of switching from headers to dynamic filter metadata: #146, this shall not be a problem any more.

**Comment by rockspore** [comment]
As was just re-realized, the ext_authz sending dynamic metadata feature was only introduced in Envoy 1.16.0 (Istio 1.8 still uses Envoy 1.15.x). So this issue will have to wait till Envoy 1.16+ is widely adopted.

**Comment by theganyo** [comment]
I think we could still do this... but we'd need to document the need to set it for older Envoys.

**Comment by rockspore** [comment]
Please see the updates at https://github.com/apigee/apigee-remote-service-cli/issues/165. It's probably better not to do this.
