### ISSUE TITLE
Integration Testing

### ISSUE THREAD

**Issue by theganyo** [apigee/apigee-remote-service-envoy#16]

**Comment by rockspore** [comment]
We now have established workflows to do most of the functionalities with Hybrid and CG SaaS.

The code has much room to be refactored and made more concise.

**Comment by theganyo** [comment]
We should also add nightly load/performance test.

**Comment by rockspore** [comment]
Needs to add a flow to test analytics service account, and fully automates it if possible. The current setting is using the GKE workload identity.

**Comment by rockspore** [comment]
All three major Apigee platforms are being tested. Closing this issue now. New issues will be opened for further improvements and enhancements.
