### ISSUE TITLE
Twelve factor app guidelines: using environment variables for configuration

### ISSUE THREAD

**Issue by regel** [apigee/apigee-remote-service-envoy#165]
## What's missing?

The go app currently uses cobra to read a 'config' file for all its configuration settings. This config file contains configuration variables, and secrets, that a user cannot override easily using environment variable(s).

## Your preferred solution

https://12factor.net/config

Using APIGEE_X_Y_Z* environment variables to override settings would simplify deployment. Can the current implementation be extended with [viper](https://github.com/spf13/viper) to support this feature?

With Kubernetes it will also open the possibility to use separate Secret(s) and ConfigMap to store config variables.

**Comment by theganyo** [comment]
@regel Thanks for your suggestion! We'll absolutely consider this.
