### ISSUE TITLE
Use metadata for target matching?

### ISSUE THREAD

**Issue by rockspore** [apigee/apigee-remote-service-envoy#166]
If we are to support this globally, I think we can add such a field `target_metadata` in `AuthConfig` and make it exclusive with `target_header`.

The format of the value could be `metadata_namespace.field_name`, which requires the field to be with depth 1 and no more.

Any thoughts?

**Comment by rockspore** [comment]
`target_metadata` seems confusing...may need a better name.

**Comment by theganyo** [comment]
As discussed elsewhere, we'll add a metadata element `apigee_target`. If present, this will override the `target_header` specified in the config.
