### ISSUE TITLE
mTLS support between adapter and runtime

### ISSUE THREAD

**Issue by rockspore** [apigee/apigee-remote-service-envoy#170]
https://github.com/apigee/apigee-remote-service-envoy/blob/7bc548fa5329bc430879fb869a1971b899ff2cad/server/config.go#L149

This field was used for mTLS with fluentd, which is now gone.

We could remove it, or use it to add mTLS support for OPDK analytics.

**Comment by rockspore** [comment]
WDYT @theganyo ?

**Comment by theganyo** [comment]
Do we have a requirement for OPDK mTLS?

**Comment by rockspore** [comment]
> Do we have a requirement for OPDK mTLS?

I don't know of any. It's just a possibility in theory.

**Comment by theganyo** [comment]
Ok. It should be simple to add anyway.

**Comment by rockspore** [comment]
I just realize we don't really support mTLS between the adapter and the `remote-service` proxy any way. So it seems cleaner to just remove this.

**Comment by theganyo** [comment]
Ok, yeah, let's wait until it's a real requirement.

**Comment by rockspore** [comment]
It seems to be a real requirement now. And this extends to both the analytics and communication with other runtime endpoints (remote-service proxy) for OPDK.
