### ISSUE TITLE
load envconfigs (proxy configs) files via command line flag

### ISSUE THREAD

**Issue by rockspore** [apigee/apigee-remote-service-envoy#201]
See #189 for reference.

Will use the flag `--proxy-config` instead of `--operation-config`

**Comment by rockspore** [comment]
`--api-configs` seems better amid PR: #200

**Comment by rockspore** [comment]
`viper` uses mapstructure instead of yaml package to perform unmarshaling. There is additional complexity in supporting directly loading inlined envconfigs (name subject to change). I will be putting this support on hold.

For now, we will support loading the configs from the `references` in the config or via command-line flag.

**Comment by theganyo** [comment]
Given latest naming choice, should probably be `--environment-configs`.
