### ISSUE TITLE
Request products from all envs only in multi-env mode

### ISSUE THREAD

**Issue by rockspore** [apigee/apigee-remote-service-envoy#211]
Currently, the filter for environments in the `/products` proxy endpoint is turned off such that it will always return all API products in the organization. This is not optimal since the adapter is still widely used in the single-env case.

We will turn the filter back on by default and take the boolean value via the request to `/products`. The adapter will send true in single-env mode and false in multi-env one.

Changes to the `remote-service` proxy will be needed in the -cli repo.

**Comment by theganyo** [comment]
I don't think any changes are needed here.
