### ISSUE TITLE
APISpec BasePath must be unique within an env

### ISSUE THREAD

**Issue by theganyo** [apigee/apigee-remote-service-envoy#237]
We currently force an APISpec.ID to be unique within an EnvironmentSpec. However, IDs are subject to APISpec.BasePath discrimination as well.

**Comment by rockspore** [comment]
Why don't we force basepaths to be unique within one env spec?

**Comment by theganyo** [comment]
Good point. But actually, now I'm not sure this issue is valid at all. Per the Apigee docs, the name must be unique within an organization. See: https://docs.apigee.com/api-platform/reference/api-proxy-configuration-reference#baseconfiguration

**Comment by theganyo** [comment]
Ok. Based on external discussion, we will ensure that BasePath is unique, but the restriction on ID can be removed.
