### ISSUE TITLE
interrupt signal after a request not exiting

### ISSUE THREAD

**Issue by theganyo** [apigee/apigee-remote-service-envoy#259]
Once a request is processed, an interrupt causes the following to be logged doesn't cleanly close the server:

```
2021-06-03T16:27:25.665-0700	INFO	apigee-remote-service-envoy/main.go:227	shutdown signal: interrupt
```

**Comment by rockspore** [comment]
Could this be due to the `StreamAccessLog` will stay open at least for a minute?

**Comment by theganyo** [comment]
No, it never shuts down.
