### ISSUE TITLE
In `proxy` mode, API products' operations' path should be matched against subpath

### ISSUE THREAD

**Issue by rockspore** [apigee/apigee-remote-service-envoy#276]
subpath refers to the path after the basepath is stripped.

**Comment by theganyo** [comment]
@srinandan I want to revisit this... shouldn't we strip the base path regardless of whether the API Product is in remote-service (EA) or proxy (EG) mode? My reasoning is basically:

API Product's path never includes the base path.
Env Config does declare a base path, so we should strip it.

Classic Envoy Adapter config doesn't have a base path. So, of course, the API Product's remote-service doesn't consider any base path - it's not really relevant that it's the entire path.

The one instance that could be confusing is if a user was deploying both EA config types at the same time and using a shared API Product remote-service configuration. In that case, the classic path and the new path would not match unless the user specified a single "/" for their base path. This seems like it would be an extreme outlier case, though, and even then could still simply be handled by the user adding a new path to their API Product remote-service.

Thoughts?

**Comment by theganyo** [comment]
In a discussion with Nandan, we agreed that it should operate as I've described above. We should always strip the base path if there is one.
