### ISSUE TITLE
Command completion

### ISSUE THREAD

**Issue by theganyo** [apigee/apigee-remote-service-envoy#285]
Cobra now adds an automatic completion command. Update, verify, document.

https://github.com/spf13/cobra/releases/tag/v1.2.0

**Comment by rockspore** [comment]
EA does not have any subcommands. So this feature may not be applicable here. I updated to cobra 1.2.0 locally and no `completion` command was generated.

**Comment by theganyo** [comment]
Good point. We should update to the same version as CLI for consistency anyway.

**Comment by rockspore** [comment]
> Good point. We should update to the same version as CLI for consistency anyway.

Sounds good.
