### ISSUE TITLE
Fix broken legacy SaaS integration test

### ISSUE THREAD

**Issue by rockspore** [apigee/apigee-remote-service-envoy#313]

**Comment by rockspore** [comment]
This may not be the best issue to describe the problem.

So now that we strip the basepath off from the path to match operations in API products. But if an API product doesn't use operations but the old-fashioned "apiResources" (basically a list of path prefixes), this is going to be very confusing, like the change I have to make for this issue. And it's probably inconsistent with how MP treats it.

**Comment by rockspore** [comment]
Ideally, we need to also send the basepath to the Authenticate() from golib.

- If the API product is configured with operations, then we match the "api" first, then the stripped path.
- If not, then we should match the full path prefix with "apiResources".

**Comment by theganyo** [comment]
Perhaps we need to discuss your concerns further because using base path with API Products is exactly what we decided (https://github.com/apigee/apigee-remote-service-envoy/issues/276) that we don't want and doing otherwise would be inconsistent with the MP.
