### ISSUE TITLE
Fix wildcard basepath stripping

### ISSUE THREAD

**Issue by rockspore** [apigee/apigee-remote-service-envoy#331]
When any wlidcard is present in the basepath, the current matching implementation will attempt to find a complete match for the request path and if none is found it will return nothing. As a result:

`/a/b/c` won't be matched for `/a/*`

Moreover, even when it gets a match, for example `/a/b` gets matched with `/a/*`, it will naively try to trim the `/a/*` literal from the request path prefix, which leads to a no op. As a result, `/a/b` will be passed down to match the operations.

**Comment by theganyo** [comment]
Please provide detail.

**Comment by rockspore** [comment]
> Please provide detail.

Added description.
