### ISSUE TITLE
Error from `pem.Decode` is not checked potentially causing panic on nil pointers.

### ISSUE THREAD

**Issue by rockspore** [apigee/apigee-remote-service-envoy#359]
Code location: https://github.com/apigee/apigee-remote-service-envoy/blob/1e7bb20936f560d53d4a93b6730fba112eeb0ca4/server/authmanager.go#L144

**Comment by rockspore** [comment]
Was there any specific reason that the error was ignored?

**Comment by theganyo** [comment]
I think it should never happen, but it just looks like an oversight.

**Comment by rockspore** [comment]
I realize pem.Decode doesn't return errors. The second return is the rest of the bytes. Right now nil-check is performed but not in the `2.0.3` release. I will do a cherry pick.
