### ISSUE TITLE
Product list not being updated

### ISSUE THREAD

**Issue by gautambaghel** [apigee/apigee-remote-service-envoy#406]
Issues filed on Github are not subject to service level agreements (SLAs) and responses 
should be assumed to be on an ad-hoc volunteer basis. The Apigee community board is 
recommended for community support and is regularly checked by Apigee experts. Apigee
customers should use formal support channels. 
See the `Get help!` page in the wiki for more information.

---
### Describe your issue
What are you seeing? 

* Product not being loaded - `retrieved 0 products, kept 0`

What were you expecting?

* Product, App, and developer all definitely exist in Apigee

Which playbooks did you follow?

* Using [this provider](https://registry.terraform.io/providers/scastria/apigee/latest/docs/resources/product)

What were the results of that investigation?

* Sometimes the product does appear when configured through the Google UI but never through the terraform provider

What other investigative actions did you take?

* Different config options for product, app, and developer keys

### What's your environment?
What is your environment?

* Apigee on Google Cloud deployed via [this module](https://github.com/apigee/terraform-modules)
* The remote proxy running on a GKE cluster

What version are you running?

* 2.1.1

What Apigee environment (eg. hybrid, SaaS, OPDK)?

* Saas - Google Cloud

What is your OS and version?
What version of Envoy?
If you're using Kubernetes and/or Istio - what are their versions?

* k8s - 1.27

Is there anything unique about your deployment?

### What's your Configuration?
What is your configuration for apigee-remote-service-envoy?

* vanilla configuration from the [guide here](https://cloud.google.com/apigee/docs/api-platform/envoy-adapter/v2.0.x/example-hybrid#create-sample-configuration-files)

What is your configuration for envoy?
Be sure to exclude any sensitive information.

### Steps to Reproduce
Can your issue be recreated?
* Yes

Will we be able to recreate your issue?
* Yes

If so, how can we recreate it?
* Follow the [repository here](https://github.com/gautambaghel/consul-k8s-apigee-x)

### Additional context
Anything else you can tell us that might be helpful?

### Attach relevant logs
Attach relevant log files, preferably at the debug level, and filtered as narrowly as possible
to only the lines dealing with the request where you are seeing the issue.
We'll likely at least need logs from `apigee-remote-service-envoy` and `envoy`.

**Comment by gautambaghel** [comment]
```
│ 2023-08-25T02:49:19.673Z    DEBUG    product/manager.go:244    retrieved 0 products, kept 0                                                                                        │
│ 2023-08-25T02:49:48.238Z    DEBUG    server/authmanager.go:110    setting internal JWT                                                                                             │
│ 2023-08-25T02:50:18.254Z    DEBUG    server/authmanager.go:110    setting internal JWT                                                                                             │
│ 2023-08-25T02:50:48.257Z    DEBUG    server/authmanager.go:110    setting internal JWT                                                                                             │
│ 2023-08-25T02:51:18.262Z    DEBUG    server/authmanager.go:110    setting internal JWT    
```

**Comment by theganyo** [comment]
Most likely the environment(s) set for the API Product(s) do not match the the environment in the Envoy Adapter configuration.

**Comment by gautambaghel** [comment]
It's being set by terraform to "env" everywhere, I checked the Google UI too

* https://github.com/gautambaghel/consul-k8s-apigee-x/blob/main/infra/variables.tf#L106
* https://github.com/gautambaghel/consul-k8s-apigee-x/blob/main/app/apigee.tf#L32
* https://github.com/gautambaghel/consul-k8s-apigee-x/blob/main/app/variables.tf#L33

**Comment by theganyo** [comment]
Since you're apparently not getting any products and the client is not logging any errors, the issue must be on the Apigee side when retrieving the product list.  I would suggest using the debugger on the proxy in the UI to see what happens with the request when you start the Envoy Adapter.

**Comment by gautambaghel** [comment]
So it's hitting the Send Product List method -> Which goes to Products Callout and it's returning

the overall workflow is:

Lookup product -> Parse Product cache -> Get runtime version (1.1.1) -> Send Product List ... and that returns

`{ "apiProduct": [ ] }`

this payload but there's clearly a product in my environment with a developer app attached to it

**Comment by gautambaghel** [comment]
<img width="1045" alt="Screenshot 2023-08-29 at 12 10 27 PM" src="https://github.com/apigee/apigee-remote-service-envoy/assets/22324290/196a4c5e-ae83-44c3-afa8-7a2d0b77f3e7">

I do have an operation attached to it

https://github.com/gautambaghel/consul-k8s-apigee-x/blob/main/app/apigee.tf#L37

**Comment by theganyo** [comment]
Everything looks right to me, then. You may need to open a case with the Apigee X team so they can look closer as to why it's not giving the list of API Products to the remote-service proxy.
