### ISSUE TITLE
NG SaaS analytics upload

### ISSUE THREAD

**Issue by rockspore** [apigee/apigee-remote-service-envoy#42]
In NG SaaS the Apigee runtime instance and the Apigee Adapter inevitably reside in different clusters. So the adapter has to find a different way of sending analytics now that the UDCA endpoint in the runtime is unreachable.

Either a UDCA is deployed along with the adapter or a "legacy" way is used. More investigation is on the way.

**Comment by srinandan** [comment]
I came up with some instructions here: https://github.com/srinandan/apigee-envoy-udca

**Comment by theganyo** [comment]
I'd like to see if we can bypass UDCA entirely - for both Ng Saas and Hybrid (at least outside of the mesh, if not inside as well). That would vastly simplify the requirements we'd have to otherwise put on customers.

**Comment by rockspore** [comment]
### Details of changes to make and desired behavior
- -cli repo:
  - If the `runtimeType` is `CLOUD` (indicating NG SaaS) during provisioning, the CLI will ask for a path to a service account json file.
  - If users plan to run the adapter in a k8s cluster, the file must exist during provisioning and it will be base64 encoded into a k8s Secret in the generated config yaml file. The given path will be irrelevant afterwards. The config file will instead specify a default path consistent with the volume mount.
  - If the file does not exist during provisioning, the given path will be assumed as the path from which the adapter can read the service account upon starting. This is for the use case of running the adapter with native Envoy proxies.
  - Certainly, users are responsible for making sure the service account has the role “Apigee Analytics Agent”.

- -envoy repo:
  - The handler reads the config for the service account file path (if available) and specifically constructs a HTTP client using the service account for the analytics manager. As such, all the authorization work is still handled entirely in this repo.

- -golib repo:
  - The analytics manager assigns a SaaS uploader if the service account file path is set in the config.
  - The SaaS uploader should add capability to handle uploading records to the GCP managed Apigee API, while maintaining the support of CG SaaS analytics endpoint.

The above is to document some useful details. Please let me know if I missed any scenario that should be supported.

**Comment by theganyo** [comment]
I think that we need to ensure that the specified SA path specified during provisioning is a valid SA file so we'll always generate the secret in the config file. As for putting a path to the SA in the config, we shouldn't need one - we should just assume it's either in the config file or a default path. In the case of native, we'll be able to read it from the config file. In the case of K8s, we'd read it from a default path that we mount to. For flexibility, though, we could add the ability to override the path in config... in which case we should ensure that any samples generated follow that override.

**Comment by theganyo** [comment]
I agree we should reuse the SaaS uploader if it's essentially unchanged. If we find there's significant variation, we should create a new uploader.

**Comment by rockspore** [comment]
> I think that we need to ensure that the specified SA path specified during provisioning is a valid SA file so we'll always generate the secret in the config file. As for putting a path to the SA in the config, we shouldn't need one - we should just assume it's either in the config file or a default path. In the case of native, we'll be able to read it from the config file. In the case of K8s, we'd read it from a default path that we mount to. For flexibility, though, we could add the ability to override the path in config... in which case we should ensure that any samples generated follow that override.

Makes sense! I made the updates.
