### ISSUE TITLE
Perf test with the optimized StreamAccessLog service

### ISSUE THREAD

**Issue by rockspore** [apigee/apigee-remote-service-envoy#77]
It'll be worth noting how Envoy balances the load the streaming calls between multiple adapter instances.

**Comment by rockspore** [comment]
With the streams from the StreamAccessLog service being long-lived, Envoy does not load balance the calls to new adapter instances via autoscaling (To be clear, authorization service is nicely load balanced).

We may want to let the server close the stream periodically, for example, every 5 minutes.

**Comment by theganyo** [comment]
I take it that this means that our timeout here: https://github.com/apigee/apigee-remote-service-envoy/blob/master/main.go#L133 isn't effective for this purpose.

**Comment by rockspore** [comment]
> I take it that this means that our timeout here: https://github.com/apigee/apigee-remote-service-envoy/blob/master/main.go#L133 isn't effective for this purpose.

I didn't test as long as 10 minutes. I need to check.

**Comment by theganyo** [comment]
It's an config option, you can decrease it. If after checking, if we find need do need to explicitly allow the stream to close periodically, let's use the same configuration option for the check.

**Comment by rockspore** [comment]
> It's an config option, you can decrease it. If after checking, if we find need do need to explicitly allow the stream to close periodically, let's use the same configuration option for the check.

No that config is not effective to close the stream. This is consistent with my experience running tests locally and seeing no stream closed till everything got terminated. Perhaps this is a stream opened by the client so the server does not enforce the closure here.
