### ISSUE TITLE
Enable use of jwtProviderKey option

### ISSUE THREAD

**Issue by theganyo** [apigee/apigee-remote-service-envoy#9]
See:
https://github.com/apigee/apigee-remote-service-envoy/commit/e5b67dd81b49a16518ba10697362d2dc8f9d74a6

Requires evaluation and design.

**Comment by rockspore** [comment]
Have we basically dropped Istio 1.4 support (Hybrid 1.3+ uses at least Istio 1.5)?

**Comment by theganyo** [comment]
+ @srinandan can answer

**Comment by srinandan** [comment]
Yes, we can drop support for Istio 1.4 and earlier
