### ISSUE TITLE
Update integration tests for operations

### ISSUE THREAD

**Issue by theganyo** [apigee/apigee-remote-service-envoy#93]
For each API Product, the following occurs:
- If JWT token, match scopes to product. If match, continue checks below. If not, authorization fails.
- Has OperationGroup
    - The OperationConfig.api_source is checked against the target request header
    - Each Operation’s paths and methods is checked against the request
    - If there’s any match, the request is authorized.
    - If no matches, continue checks below
- No OperationGroup
    - “apigee-remote-service-targets” attribute is checked against the target request header
    - The API Product’s paths are checked against the request
    - If there’s a match, the request is authorized. If not, authorization fails.

Quotas:
- Quota selection
    - All authorized OperationConfig Quotas are selected
    - For any authorized OperationConfig that doesn’t have a Quota, its API Product Quota is selected
    - All authorized API Product Quotas are selected for Products that do not have an OperationGroup
- Quota application
    - All selected quotas are incremented
    - If any quota is exceeded, the request is denied

**Comment by rockspore** [comment]
Integration tests include operations now.
